package com.example.ahxre.pokemon;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;


public class ability extends AppCompatActivity {
    int i  ;String s;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ability);
        ImageView imageView = (ImageView)findViewById(R.id.imageView2);
        TextView txvab =(TextView)findViewById(R.id.txvab);
        Intent it = getIntent();
        i = it.getIntExtra("ability",0);
        txvab.setText(getIntent().getStringExtra("name"));
        if(i==0)
        {
            imageView.setImageResource(R.drawable.b0); //根據Itent送過來的listview的position顯示圖片
        }
        if(i==1)
        {
            imageView.setImageResource(R.drawable.b1);
        }
        if(i==2)
        {
            imageView.setImageResource(R.drawable.b2);
        }
        if(i==3)
        {
            imageView.setImageResource(R.drawable.b3);
        }
        if(i==4)
        {
            imageView.setImageResource(R.drawable.b4);
        }
        if(i==5)
        {
            imageView.setImageResource(R.drawable.b5);
        }
        if(i==6)
        {
            imageView.setImageResource(R.drawable.b6);
        }
        if(i==7)
        {
            imageView.setImageResource(R.drawable.b7);
        }
        if(i==8)
        {
            imageView.setImageResource(R.drawable.b8);
        }
        if(i==9)
        {
            imageView.setImageResource(R.drawable.b9);

        }
        if(i==10)
        {
            imageView.setImageResource(R.drawable.b10);
        }
        if(i==11)
        {
            imageView.setImageResource(R.drawable.b11);
        }
        if(i==12)
        {
            imageView.setImageResource(R.drawable.b12);
        }
        if(i==13)
        {
            imageView.setImageResource(R.drawable.b13);
        }
        if(i==14)
        {
            imageView.setImageResource(R.drawable.b14);
        }
        if(i==15)
        {
            imageView.setImageResource(R.drawable.b15);
        }
        if(i==16)
        {
            imageView.setImageResource(R.drawable.b16);
        }
        if(i==17)
        {
            imageView.setImageResource(R.drawable.b17);
        }
        if(i==18)
        {
            imageView.setImageResource(R.drawable.b18);
        }
        if(i==19)
        {
            imageView.setImageResource(R.drawable.b19);
        }
        if(i==20)
        {
            imageView.setImageResource(R.drawable.b20);
        }
        if(i==21)
        {
            imageView.setImageResource(R.drawable.b21);
        }
        if(i==22)
        {
            imageView.setImageResource(R.drawable.b22);
        }
        if(i==23)
        {
            imageView.setImageResource(R.drawable.b23);
        }
        if(i==24)
        {
            imageView.setImageResource(R.drawable.b24);
        }
        if(i==25)
        {
            imageView.setImageResource(R.drawable.b25);
        }
        if(i==25)
        {
            imageView.setImageResource(R.drawable.b25);

        }
        if(i==26)
        {
            imageView.setImageResource(R.drawable.b26);
        }
        if(i==27)
        {
            imageView.setImageResource(R.drawable.b27);
        }
        if(i==28)
        {
            imageView.setImageResource(R.drawable.b28);
        }
        if(i==29)
        {
            imageView.setImageResource(R.drawable.b29);
        }
        if(i==30)
        {
            imageView.setImageResource(R.drawable.b30);
        }
        if(i==31)
        {
            imageView.setImageResource(R.drawable.b31);
        }
        if(i==32)
        {
            imageView.setImageResource(R.drawable.b32);
        }
        if(i==33)
        {
            imageView.setImageResource(R.drawable.b33);
        }
        if(i==34)
        {
            imageView.setImageResource(R.drawable.b34);
        }
        if(i==35)
        {
            imageView.setImageResource(R.drawable.b35);
        }
        if(i==36)
        {
            imageView.setImageResource(R.drawable.b36);
        }
        if(i==37)
        {
            imageView.setImageResource(R.drawable.b37);
        }
        if(i==38)
        {
            imageView.setImageResource(R.drawable.b38);
        }
        if(i==39)
        {
            imageView.setImageResource(R.drawable.b39);
        }
        if(i==40)
        {
            imageView.setImageResource(R.drawable.b40);
        }
        if(i==41)
        {
            imageView.setImageResource(R.drawable.b41);
        }
        if(i==42)
        {
            imageView.setImageResource(R.drawable.b42);
        }
        if(i==43)
        {
            imageView.setImageResource(R.drawable.b43);
        }
        if(i==44)
        {
            imageView.setImageResource(R.drawable.b44);
        }
        if(i==45)
        {
            imageView.setImageResource(R.drawable.b45);
        }
        if(i==46)
        {
            imageView.setImageResource(R.drawable.b46);
        }
        if(i==47)
        {
            imageView.setImageResource(R.drawable.b47);
        }
        if(i==48)
        {
            imageView.setImageResource(R.drawable.b48);
        }
        if(i==49)
        {
            imageView.setImageResource(R.drawable.b49);
        }
        if(i==50)
        {
            imageView.setImageResource(R.drawable.b50);
        }
        if(i==51)
        {
            imageView.setImageResource(R.drawable.b51);
        }
        if(i==52)
        {
            imageView.setImageResource(R.drawable.b52);
        }
        if(i==53)
        {
            imageView.setImageResource(R.drawable.b53);
        }
        if(i==54)
        {
            imageView.setImageResource(R.drawable.b54);
        }
        if(i==55)
        {
            imageView.setImageResource(R.drawable.b55);
        }
        if(i==56)
        {
            imageView.setImageResource(R.drawable.b56);
        }
        if(i==57)
        {
            imageView.setImageResource(R.drawable.b57);
        }
        if(i==58)
        {
            imageView.setImageResource(R.drawable.b58);
        }
        if(i==59)
        {
            imageView.setImageResource(R.drawable.b59);
        }
        if(i==60)
        {
            imageView.setImageResource(R.drawable.b60);
        }
        if(i==61)
        {
            imageView.setImageResource(R.drawable.b61);
        }
        if(i==62)
        {
            imageView.setImageResource(R.drawable.b62);
        }
        if(i==63)
        {
            imageView.setImageResource(R.drawable.b63);
        }
        if(i==64)
        {
            imageView.setImageResource(R.drawable.b64);
        }
        if(i==65)
        {
            imageView.setImageResource(R.drawable.b65);
        }
        if(i==66)
        {
            imageView.setImageResource(R.drawable.b66);
        }
        if(i==67)
        {
            imageView.setImageResource(R.drawable.b67);
        }
        if(i==68)
        {
            imageView.setImageResource(R.drawable.b68);
        }
        if(i==69)
        {
            imageView.setImageResource(R.drawable.b69);
        }
        if(i==70)
        {
            imageView.setImageResource(R.drawable.b70);
        }
        if(i==71)
        {
            imageView.setImageResource(R.drawable.b71);
        }
        if(i==72)
        {
            imageView.setImageResource(R.drawable.b72);
        }
        if(i==73)
        {
            imageView.setImageResource(R.drawable.b73);
        }
        if(i==74)
        {
            imageView.setImageResource(R.drawable.b74);
        }
        if(i==75)
        {
            imageView.setImageResource(R.drawable.b75);
        }
        if(i==76)
        {
            imageView.setImageResource(R.drawable.b76);
        }
        if(i==77)
        {
            imageView.setImageResource(R.drawable.b77);
        }
        if(i==78)
        {
            imageView.setImageResource(R.drawable.b78);
        }
        if(i==79)
        {
            imageView.setImageResource(R.drawable.b79);
        }
        if(i==80)
        {
            imageView.setImageResource(R.drawable.b80);
        }
        if(i==81)
        {
            imageView.setImageResource(R.drawable.b81);
        }
        if(i==82)
        {
            imageView.setImageResource(R.drawable.b82);
        }
        if(i==83)
        {
            imageView.setImageResource(R.drawable.b83);
        }
        if(i==84)
        {
            imageView.setImageResource(R.drawable.b84);
        }
        if(i==85)
        {
            imageView.setImageResource(R.drawable.b85);
        }
        if(i==86)
        {
            imageView.setImageResource(R.drawable.b86);
        }
        if(i==87)
        {
            imageView.setImageResource(R.drawable.b87);
        }
        if(i==88)
        {
            imageView.setImageResource(R.drawable.b88);
        }
        if(i==89)
        {
            imageView.setImageResource(R.drawable.b89);
        }
        if(i==90)
        {
            imageView.setImageResource(R.drawable.b90);
        }
        if(i==91)
        {
            imageView.setImageResource(R.drawable.b91);
        }
        if(i==92)
        {
            imageView.setImageResource(R.drawable.b92);
        }
        if(i==93)
        {
            imageView.setImageResource(R.drawable.b93);
        }
        if(i==94)
        {
            imageView.setImageResource(R.drawable.b94);
        }
        if(i==95)
        {
            imageView.setImageResource(R.drawable.b95);
        }
        if(i==96)
        {
            imageView.setImageResource(R.drawable.b96);
        }
        if(i==97)
        {
            imageView.setImageResource(R.drawable.b97);
        }
        if(i==98)
        {
            imageView.setImageResource(R.drawable.b98);
        }
        if(i==99)
        {
            imageView.setImageResource(R.drawable.b99);

        }
        if(i==100)
        {
            imageView.setImageResource(R.drawable.b100);
        }
        if(i==101)
        {
            imageView.setImageResource(R.drawable.b101);
        }
        if(i==102)
        {
            imageView.setImageResource(R.drawable.b102);
        }
        if(i==103)
        {
            imageView.setImageResource(R.drawable.b103);
        }
        if(i==104)
        {
            imageView.setImageResource(R.drawable.b104);
        }
        if(i==105)
        {
            imageView.setImageResource(R.drawable.b105);
        }
        if(i==106)
        {
            imageView.setImageResource(R.drawable.b106);
        }
        if(i==107)
        {
            imageView.setImageResource(R.drawable.b107);
        }
        if(i==108)
        {
            imageView.setImageResource(R.drawable.b108);
        }
        if(i==109)
        {
            imageView.setImageResource(R.drawable.b109);
        }
        if(i==110)
        {
            imageView.setImageResource(R.drawable.b110);
        }
        if(i==111)
        {
            imageView.setImageResource(R.drawable.b111);
        }
        if(i==112)
        {
            imageView.setImageResource(R.drawable.b112);
        }
        if(i==113)
        {
            imageView.setImageResource(R.drawable.b113);
        }
        if(i==114)
        {
            imageView.setImageResource(R.drawable.b114);
        }
        if(i==115)
        {
            imageView.setImageResource(R.drawable.b115);
        }
        if(i==116)
        {
            imageView.setImageResource(R.drawable.b116);
        }
        if(i==117)
        {
            imageView.setImageResource(R.drawable.b117);
        }
        if(i==118)
        {
            imageView.setImageResource(R.drawable.b118);
        }
        if(i==119)
        {
            imageView.setImageResource(R.drawable.b119);
        }
        if(i==120)
        {
            imageView.setImageResource(R.drawable.b120);
        }
        if(i==121)
        {
            imageView.setImageResource(R.drawable.b121);
        }
        if(i==122)
        {
            imageView.setImageResource(R.drawable.b122);
        }
        if(i==123)
        {
            imageView.setImageResource(R.drawable.b123);
        }
        if(i==124)
        {
            imageView.setImageResource(R.drawable.b124);
        }
        if(i==125)
        {
            imageView.setImageResource(R.drawable.b125);
        }
        if(i==126)
        {
            imageView.setImageResource(R.drawable.b126);
        }
        if(i==127)
        {
            imageView.setImageResource(R.drawable.b127);
        }
        if(i==128)
        {
            imageView.setImageResource(R.drawable.b128);
        }
        if(i==129)
        {
            imageView.setImageResource(R.drawable.b129);
        }
        if(i==130)
        {
            imageView.setImageResource(R.drawable.b130);
        }
        if(i==131)
        {
            imageView.setImageResource(R.drawable.b131);
        }
        if(i==132)
        {
            imageView.setImageResource(R.drawable.b132);
        }
        if(i==133)
        {
            imageView.setImageResource(R.drawable.b133);
        }
        if(i==134)
        {
            imageView.setImageResource(R.drawable.b134);
        }
        if(i==135)
        {
            imageView.setImageResource(R.drawable.b135);
        }
        if(i==136)
        {
            imageView.setImageResource(R.drawable.b136);
        }
        if(i==137)
        {
            imageView.setImageResource(R.drawable.b137);
        }
        if(i==138)
        {
            imageView.setImageResource(R.drawable.b138);
        }
        if(i==139)
        {
            imageView.setImageResource(R.drawable.b139);
        }
        if(i==140)
        {
            imageView.setImageResource(R.drawable.b140);
        }
        if(i==141)
        {
            imageView.setImageResource(R.drawable.b141);
        }
        if(i==142)
        {
            imageView.setImageResource(R.drawable.b142);
        }
        if(i==143)
        {
            imageView.setImageResource(R.drawable.b143);
        }
        if(i==144)
        {
            imageView.setImageResource(R.drawable.b144);
        }
        if(i==145)
        {
            imageView.setImageResource(R.drawable.b145);
        }
        if(i==146)
        {
            imageView.setImageResource(R.drawable.b146);
        }
        if(i==147)
        {
            imageView.setImageResource(R.drawable.b147);
        }
        if(i==148)
        {
            imageView.setImageResource(R.drawable.b148);
        }
        if(i==149)
        {
            imageView.setImageResource(R.drawable.b149);
        }
        if(i==150)
        {
            imageView.setImageResource(R.drawable.b150);
        }



    }
    public void onClick(View view)
    {
        Intent it = new Intent(this,MainActivity.class);
        startActivity(it);
    }
}
